package ar.edu.unlp.turnos.catalog.user.domain.model;

import java.time.Instant;
import java.util.List;
import java.util.Objects;
import java.util.UUID;
import lombok.Builder;
import lombok.Getter;

/**
 * End user of the KMP application (section 3.2 of the statement).
 *
 * <p>The shape is compatible with the user generated by JHipster: the tables keep the
 * {@code jhi_} prefix, the credential is stored as a hash and the authorities are a many to
 * many relationship, so both deployments expose the same observable data.</p>
 *
 * <p>Decisions worth documenting:</p>
 *
 * <ul>
 *   <li>{@code publicId} is the stable identifier handed out to other services (the
 *       {@code externalPatientId} of contract v1). It is generated here, never accepted
 *       from the client, and it survives a change of login;</li>
 *   <li>{@code passwordHash} is a BCrypt hash, never the clear password: the clear value
 *       only exists while the registration or the login is being processed and it is never
 *       written to a response nor to a log;</li>
 *   <li>{@code activated} is true from the registration: there is no e-mail verification
 *       step (section 3.2 of the statement);</li>
 *   <li>the technical account of the catedra is a <strong>different</strong> identity: it
 *       lives in {@code catedra_integration} and never reaches this model.</li>
 * </ul>
 *
 * <p>Pure domain model: no Spring, no JPA, no DTOs.</p>
 */
@Getter
@Builder(toBuilder = true)
public class EndUser {

    /** Only role an end user can hold. */
    public static final String DEFAULT_AUTHORITY = "ROLE_USER";

    private final Long id;
    private final UUID publicId;
    private final String login;
    private final String passwordHash;
    private final String firstName;
    private final String lastName;
    private final String email;
    private final String imageUrl;
    private final String langKey;
    private final boolean activated;
    private final Instant createdAt;
    private final Instant modifiedAt;
    private final String lastModifiedBy;
    private final List<String> authorities;

    /**
     * Builds the representation of a user that has just been registered: active from the
     * start, holding the only role an end user can hold, with its public identity already
     * assigned.
     *
     * @param registration validated registration data
     * @param publicId     stable identifier generated by this service
     * @param passwordHash BCrypt hash of the password
     * @param createdAt    instant of the registration
     * @return the user ready to be persisted
     */
    public static EndUser registered(UserRegistration registration, UUID publicId,
                                     String passwordHash, Instant createdAt) {
        if (passwordHash == null || passwordHash.isBlank()) {
            throw new IllegalArgumentException("A registered user must store a password hash.");
        }
        return EndUser.builder()
                .publicId(publicId)
                .login(registration.getLogin())
                .passwordHash(passwordHash)
                .firstName(registration.getFirstName())
                .lastName(registration.getLastName())
                .email(registration.getNormalizedEmail())
                .imageUrl(registration.getImageUrl())
                .langKey(registration.getLangKey())
                .activated(true)
                .createdAt(createdAt)
                .modifiedAt(createdAt)
                .lastModifiedBy(registration.getLogin())
                .authorities(List.of(DEFAULT_AUTHORITY))
                .build();
    }

    /**
     * @return true when the credential of this user can be verified, i.e. a hash is stored
     */
    public boolean hasStoredCredential() {
        return Objects.nonNull(passwordHash) && !passwordHash.isBlank();
    }
}
