-- End users of the KMP application (section 3.2 of the statement).
--
-- The model is compatible with the user generated by JHipster: the tables keep the jhi_
-- prefix, the password is stored as a hash and the authorities are a many to many
-- relationship, so a JHipster deployment and this service expose the same observable data.
--
-- This service is the OWNER of these tables. The technical integration account of the
-- catedra is a DIFFERENT identity and lives in catedra_integration (V1); its credentials
-- never reach this table, nor the KMP application.

CREATE TABLE jhi_user (
    id               BIGSERIAL    PRIMARY KEY,
    -- Stable identifier handed out to other services (externalPatientId of contract v1).
    -- It never changes, even if the login does.
    public_id        UUID         NOT NULL,
    login            VARCHAR(50)  NOT NULL,
    -- BCrypt hash: 60 characters. The clear password never touches this table. The column
    -- is wider than BCrypt needs so a future move to Argon2 does not require a migration.
    password_hash    VARCHAR(120) NOT NULL,
    first_name       VARCHAR(50),
    last_name        VARCHAR(50),
    email            VARCHAR(254) NOT NULL,
    image_url        VARCHAR(254),
    lang_key         VARCHAR(10),
    -- The user is active from the moment of the registration: there is no e-mail
    -- verification step (section 3.2 of the statement).
    activated        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ  NOT NULL,
    modified_at      TIMESTAMPTZ  NOT NULL,
    last_modified_by VARCHAR(50),

    CONSTRAINT uq_jhi_user_login UNIQUE (login),
    CONSTRAINT uq_jhi_user_email UNIQUE (email),
    CONSTRAINT uq_jhi_user_public_id UNIQUE (public_id),
    CONSTRAINT ck_jhi_user_login_length CHECK (char_length(login) >= 3),
    CONSTRAINT ck_jhi_user_password_hash CHECK (char_length(password_hash) >= 60)
);

-- One row per role. Seeded with the only role an end user can hold.
CREATE TABLE jhi_authority (
    name VARCHAR(50) PRIMARY KEY,

    CONSTRAINT ck_jhi_authority_name CHECK (name LIKE 'ROLE\_%')
);

INSERT INTO jhi_authority (name) VALUES ('ROLE_USER');

-- Ownership of a role by a user.
CREATE TABLE jhi_user_authority (
    user_id        BIGINT      NOT NULL,
    authority_name VARCHAR(50) NOT NULL,

    CONSTRAINT pk_jhi_user_authority PRIMARY KEY (user_id, authority_name),
    CONSTRAINT fk_jhi_user_authority_user
        FOREIGN KEY (user_id) REFERENCES jhi_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_jhi_user_authority_authority
        FOREIGN KEY (authority_name) REFERENCES jhi_authority (name)
);
